import Link from "next/link";
import { count, desc, eq } from "drizzle-orm";
import { db } from "@/db";
import { calculatorSubmissions, enquiries, insights, media, projects } from "@/db/schema";
import { AdminPageHeader, Badge, StatCard, Table } from "@/components/admin/admin-ui";
import { formatDateShort } from "@/lib/utils";

async function countRows(q: Promise<{ c: number }[]>) {
  const [row] = await q;
  return Number(row?.c ?? 0);
}

export default async function DashboardPage() {
  const [projectCount, publishedCount, mediaCount, enquiryNew, insightCount, submissionCount] = await Promise.all([
    countRows(db.select({ c: count() }).from(projects)),
    countRows(db.select({ c: count() }).from(projects).where(eq(projects.published, true))),
    countRows(db.select({ c: count() }).from(media)),
    countRows(db.select({ c: count() }).from(enquiries).where(eq(enquiries.status, "new"))),
    countRows(db.select({ c: count() }).from(insights)),
    countRows(db.select({ c: count() }).from(calculatorSubmissions)),
  ]);
  const [recentEnquiries, recentProjects, recentMedia] = await Promise.all([
    db.select().from(enquiries).orderBy(desc(enquiries.createdAt)).limit(5),
    db.select().from(projects).orderBy(desc(projects.updatedAt)).limit(5),
    db.select().from(media).orderBy(desc(media.createdAt)).limit(6),
  ]);

  return (
    <>
      <AdminPageHeader
        title="Dashboard"
        description="Everything on the public website is managed from here — no code changes required."
        actions={
          <>
            <Link href="/admin/projects/new" className="btn-primary py-2 text-sm">New project</Link>
            <Link href="/admin/media" className="btn-outline py-2 text-sm">Upload media</Link>
          </>
        }
      />
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatCard label="Projects" value={projectCount} hint={`${publishedCount} published`} href="/admin/projects" />
        <StatCard label="New enquiries" value={enquiryNew} hint="Awaiting first contact" href="/admin/enquiries" />
        <StatCard label="Media items" value={mediaCount} hint="Images and videos" href="/admin/media" />
        <StatCard label="Insights" value={insightCount} href="/admin/insights" />
        <StatCard label="Calculator estimates" value={submissionCount} hint="Generated by visitors" href="/admin/calculator" />
        <StatCard label="Calculator config" value="Live" hint="Assumptions & appliances" href="/admin/calculator" />
      </div>

      <div className="mt-10 grid gap-8 lg:grid-cols-2">
        <section>
          <div className="mb-3 flex items-center justify-between">
            <h2 className="display text-lg text-navy">Recent enquiries</h2>
            <Link href="/admin/enquiries" className="text-xs text-green-700 hover:underline">View all</Link>
          </div>
          <Table head={["Name", "Service", "Status", "Received"]}>
            {recentEnquiries.map((e) => (
              <tr key={e.id}>
                <td className="px-4 py-3 font-medium text-navy">{e.name}</td>
                <td className="px-4 py-3 text-slate-ink">{e.service || "—"}</td>
                <td className="px-4 py-3"><Badge tone={e.status === "new" ? "green" : "neutral"}>{e.status}</Badge></td>
                <td className="px-4 py-3 text-slate-ink">{formatDateShort(e.createdAt)}</td>
              </tr>
            ))}
            {!recentEnquiries.length ? <tr><td colSpan={4} className="px-4 py-6 text-center text-slate-ink">No enquiries yet.</td></tr> : null}
          </Table>
        </section>
        <section>
          <div className="mb-3 flex items-center justify-between">
            <h2 className="display text-lg text-navy">Recently updated projects</h2>
            <Link href="/admin/projects" className="text-xs text-green-700 hover:underline">Manage</Link>
          </div>
          <Table head={["Project", "Status", "Updated"]}>
            {recentProjects.map((p) => (
              <tr key={p.id}>
                <td className="px-4 py-3"><Link href={`/admin/projects/${p.id}`} className="font-medium text-navy hover:underline">{p.title}</Link></td>
                <td className="px-4 py-3"><Badge tone={p.published ? "green" : "amber"}>{p.published ? "Published" : "Draft"}</Badge></td>
                <td className="px-4 py-3 text-slate-ink">{formatDateShort(p.updatedAt)}</td>
              </tr>
            ))}
          </Table>
        </section>
      </div>

      <section className="mt-10">
        <div className="mb-3 flex items-center justify-between">
          <h2 className="display text-lg text-navy">Latest media</h2>
          <Link href="/admin/media" className="text-xs text-green-700 hover:underline">Open library</Link>
        </div>
        <div className="grid grid-cols-3 gap-3 md:grid-cols-6">
          {recentMedia.map((m) => (
            <div key={m.id} className="overflow-hidden rounded-xl border border-navy/10 bg-white">
              {m.type === "video" ? (
                <div className="flex aspect-[4/3] items-center justify-center bg-navy text-[10px] text-white">VIDEO</div>
              ) : (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={m.thumbnailUrl || m.url} alt={m.altText || m.title} className="aspect-[4/3] w-full object-cover" loading="lazy" />
              )}
              <div className="truncate px-2 py-1.5 text-[10px] text-slate-ink">{m.title || m.filename}</div>
            </div>
          ))}
        </div>
      </section>
    </>
  );
}
